### ISSUE TITLE
Sign git commits

### ISSUE THREAD

**Issue by kaspar030** [timvisee/prs#10]
"pass" allows signing of the git commits. (`pass.signcommits=true`)

We use github's branch protection to enforce that.

It would be great if prs would support this, too!

**Comment by timvisee** [comment]
I assume you're talking about GPG signing.

`prs` basically invokes the `git` command when doing operations, meaning you can use `git`s configuration to achieve this.

Simply prefix your `git` commands with `prs` to invoke it's commands within your password store.

```bash
# Enable signing in local git config in password store
prs git config commit.gpgsign true

# Commit and push (sync)
prs git status
prs git add .
prs git commit
prs git push
```

Does this suffice?

**Comment by kaspar030** [comment]
Could've thought of that. Thanks a lot!
