### ISSUE TITLE
replace external call to fzf with skim

### ISSUE THREAD

**Issue by colemickens** [timvisee/prs#18]
Hi.

Prs.exe on windows currently fails in some scenarios since I don't have FZF installed. I think it would be great if FZF were replaced with Skim, a Rust equivalent:

https://github.com/lotabout/skim

Thank you!

**Comment by timvisee** [comment]
Since I don't think Windows support will ever be added to `skim` I'll close this now.

Feel free to open this again if you have another suggestion to improve on this.
