### ISSUE TITLE
prs generate - not sure why it needs a name

### ISSUE THREAD

**Issue by colemickens** [timvisee/prs#25]
I'm just looking for a quick secure ephemeral password.

What is the meaning of passing a name, without calling `--store`?

**Comment by colemickens** [comment]
Oh, I'm silly, `--store` is to pass an alternative password store location.

Do you think it makes sense to have another subcommand, or overload this one so that it just generates without any attempt to save if no name is provided? It could even emit a warning, I suppose?

**Comment by timvisee** [comment]
`prs` works with your store by default, so `generate` tries to put it in the store by default. `--store` is only to provide a store that is different than the default.

You can generate a password without storing it as secret by providing `--stdout`

```bash
$ prs generate --stdout
*fF(49TVrW>Y7uAT]>)[A/u6
```

**Comment by colemickens** [comment]
:pray: thank you!
