### ISSUE TITLE
wl-clipboard should be mentioned as a requirement on Wayland

### ISSUE THREAD

**Issue by ivan-avalos** [timvisee/prs#3]
Hello, I built `prs` on Linux arm64, and I'm running Wayland. When I tried to copy a password, I came across this error:

```
error: failed to copy secret to clipboard
caused by: failed to set clipboard
caused by: Could not find wl-copy or wl-paste binary for clipboard support
```

After installing `wl-clipboard`, the problem was solved; but I think it should be included on the `README.md` as a dependency on Wayland.

**Comment by timvisee** [comment]
You're right!

Feel free to submit it as a PR. I'm not able to resolve it myself at this moment.
