### ISSUE TITLE
Incorrect reference, and a question

### ISSUE THREAD

**Issue by ArielHorwitz** [timvisee/prs#33]
https://github.com/timvisee/prs/blob/3d33d9dc5b842560773d337868ccd60d9130d15c/README.md?plain=1#L491

Just a small copy error, the line on `madvice` references the page for `mlock`.

I am opening an issue instead of a PR because I actually have a question I was hoping you can answer 🙏 I am trying to understand where the `mlock` and `madvice` are implemented, and I would love a pointer to this in the source code. From there I would be glad to do my own research. Thanks in advance!

**Comment by timvisee** [comment]
Of course!

`prs` depends on the `secstr` as secure container. It takes care of using `madvice` and `mlock`.

References:
- https://docs.rs/secstr/latest/secstr/struct.SecVec.html
- https://codeberg.org/valpackett/secstr/src/commit/b7e81f00ac601b3d629db0bbfd8ea31cadd41b20/src/lib.rs#L441-L444
- https://codeberg.org/valpackett/secstr/src/commit/b7e81f00ac601b3d629db0bbfd8ea31cadd41b20/src/lib.rs#L441-L444

> Just a small copy error, the line on madvice references the page for mlock.

Thanks!

**Comment by ArielHorwitz** [comment]
Thank you very much :)
